### PR TITLE
Add: search function

### PR DESCRIPTION
**Pull request by gauravsinhaweb**
files to check:
- hero.jsx
- searchHandler.js

### CODE REVIEW

**Review by mehulsatardekar — APPROVED** [review]
everything looks good from my side  and ready to merge

**Review by pankaj-prog — APPROVED** [review]
Suggestion: improve upon the naming, the names that you have used are not quite declarative which makes the code a bit difficult to read.

**Comment by gauravsinhaweb** [comment]
> Suggestion: improve upon the naming, the names that you have used are not quite declarative which makes the code a bit difficult to read.

will work upon naming variables! thanks!!

**Comment by gauravsinhaweb** [comment]
> everything looks good from my side and ready to merge

Okay!

**Pull request merged**
